version: '3.8'

services:
  modela:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
